import 'package:flutter/material.dart';
import '../services/ai_service.dart';
import '../services/app_state.dart';
import '../widgets/app_header.dart';
import 'quiz_page.dart';
import 'flashcards_page.dart';

class AiPage extends StatefulWidget { const AiPage({super.key}); @override State<AiPage> createState()=>_AiPageState(); }
class _AiPageState extends State<AiPage>{ final prompt=TextEditingController(); String result=''; bool loading=false; String mode='assistant';
Future<void> ask(String p,String m)async{if(p.trim().isEmpty)return;setState((){loading=true;result='';mode=m;});try{result=await const AiService().generate(prompt:'${AppState.instance.buildStudyContext()}\n\nطلب المستخدم:\n$p',mode:m);}catch(_){result='تعذر الوصول إلى خدمة الذكاء الاصطناعي. تحقق من الإنترنت وAI_ENDPOINT ثم حاول مرة أخرى.';}if(mounted)setState(()=>loading=false);}
@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:[const AppHeader(title:'المساعد الذكي',subtitle:'ذكاء اصطناعي مرتبط بموادك ودروسك وأخطاءك'),const SizedBox(height:18),TextField(controller:prompt,maxLines:7,decoration:const InputDecoration(hintText:'الصق محتوى الدرس أو اكتب السؤال أو المطلوب...',prefixIcon:Icon(Icons.edit_note))),const SizedBox(height:10),FilledButton.icon(onPressed:loading?null:()=>ask(prompt.text,'assistant'),icon:const Icon(Icons.send),label:const Text('تنفيذ بالذكاء الاصطناعي')),const SizedBox(height:14),Wrap(spacing:8,runSpacing:8,children:[['فهم وشرح','explain',Icons.lightbulb],['تلخيص','summary',Icons.summarize],['اختبار','questions',Icons.quiz],['بطاقات مراجعة','flashcards',Icons.style],['خريطة ذهنية','mindmap',Icons.account_tree],['تصميم مذاكرة','design',Icons.palette],['مراجعة أخطاء','review',Icons.fact_check],['حل واجب','homework',Icons.calculate]].map((x)=>ActionChip(avatar:Icon(x[2] as IconData,size:18),label:Text(x[0] as String),onPressed:loading?null:()=>ask(prompt.text.isEmpty?x[0] as String:prompt.text,x[1] as String))).toList()),const SizedBox(height:16),Wrap(spacing:10,runSpacing:10,children:[OutlinedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const QuizPage())),icon:const Icon(Icons.quiz_outlined),label:const Text('ابدأ اختبارًا الآن')),OutlinedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const FlashcardsPage())),icon:const Icon(Icons.style_outlined),label:const Text('ذاكر بالبطاقات'))]),if(loading)const Padding(padding:EdgeInsets.all(24),child:Center(child:CircularProgressIndicator())),if(result.isNotEmpty)Card(margin:const EdgeInsets.only(top:18),child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('النتيجة • $mode',style:const TextStyle(fontWeight:FontWeight.w800)),const Divider(),SelectableText(result,style:const TextStyle(fontSize:16,height:1.65))]))),const SizedBox(height:14),Card(child:ListTile(leading:const Icon(Icons.auto_awesome),title:const Text('سياق الدراسة متصل'),subtitle:Text('يتم إرسال سياق المواد والدروس والمهام والأخطاء مع الطلب عند تفعيل Backend.')))]);@override void dispose(){prompt.dispose();super.dispose();}}
