import 'package:flutter/material.dart';import '../services/app_state.dart';import '../widgets/app_header.dart';import '../widgets/section_title.dart';import '../models/study_models.dart';
class Dashboard extends StatelessWidget{const Dashboard({super.key});@override Widget build(BuildContext c)=>AnimatedBuilder(animation:AppState.instance,builder:(_,__) {final s=AppState.instance;final today=DateTime.now();final todayTasks=s.tasksFor(today);final todaySchedule=s.scheduleFor(today);return ListView(padding:const EdgeInsets.all(18),children:[const AppHeader(title:'مساعد الطالب الذكي',subtitle:'مساعدك الدراسي الشامل بالذكاء الاصطناعي'),const SizedBox(height:18),_hero(c,s),const SizedBox(height:18),const SectionTitle('اختصارات سريعة'),const SizedBox(height:10),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,childAspectRatio:1.65,crossAxisSpacing:10,mainAxisSpacing:10,children:[_q('إضافة مادة',Icons.menu_book,()=>_addSubject(c)),_q('إضافة مهمة',Icons.task_alt,()=>_addTask(c,s)),_q('جلسة مذاكرة',Icons.timer,()=>_startSession(c,s)),_q('اختبار جديد',Icons.quiz,()=>_addExam(c,s))]),const SizedBox(height:18),SectionTitle('اليوم',action:'إضافة موعد',onTap:()=>_addSchedule(c,s)),if(todaySchedule.isEmpty&&todayTasks.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('لا توجد عناصر مجدولة اليوم. أضف مهمة أو جلسة مذاكرة وابدأ.'))),...todaySchedule.map((x)=>_scheduleTile(c,s,x)),...todayTasks.map((x)=>_taskTile(c,s,x)),const SizedBox(height:18),const SectionTitle('نظرة سريعة'),const SizedBox(height:8),Row(children:[Expanded(child:_metric('تقدم التعلم','${(s.learningProgress*100).round()}%',Icons.school_rounded,c)),Expanded(child:_metric('المهام','${s.completedTasks}/${s.tasks.length}',Icons.check_circle,c)),Expanded(child:_metric('المذاكرة','${s.totalMinutes} د',Icons.timer_rounded,c))]),const SizedBox(height:18),const SectionTitle('رحلة الدراسة'),const Card(child:Padding(padding:EdgeInsets.all(16),child:Text('إضافة المحتوى  →  تنظيمه  →  فهمه  →  تلخيصه  →  مذاكرته  →  اختباره  →  مراجعة الأخطاء  →  متابعة التقدم',textAlign:TextAlign.center,style:TextStyle(height:1.7,fontWeight:FontWeight.w600))))]);});}
Widget _hero(BuildContext c,AppState s)=>Card(color:Theme.of(c).colorScheme.primaryContainer,child:Padding(padding:const EdgeInsets.all(18),child:Row(children:[CircleAvatar(radius:34,backgroundColor:Theme.of(c).colorScheme.primary,child:const Icon(Icons.auto_awesome,color:Colors.white,size:32)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('مستوى ${s.level} • ${s.xp} XP',style:Theme.of(c).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:6),Text('أكملت ${(s.learningProgress*100).round()}% من الدروس و${(s.taskProgress*100).round()}% من المهام.'),const SizedBox(height:10),LinearProgressIndicator(value:s.learningProgress,minHeight:8,borderRadius:BorderRadius.circular(8))]))]));
Widget _q(String t,IconData i,VoidCallback f)=>Card(child:InkWell(onTap:f,borderRadius:BorderRadius.circular(16),child:Padding(padding:const EdgeInsets.all(12),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(i),const SizedBox(height:6),Text(t,style:const TextStyle(fontWeight:FontWeight.w700))]))));
Widget _taskTile(BuildContext c,AppState s,StudyTask x)=>Card(child:CheckboxListTile(value:x.completed,onChanged:(_)=>s.toggleTask(x),title:Text(x.title,style:TextStyle(decoration:x.completed?TextDecoration.lineThrough:null)),subtitle:Text('${x.subject} • أولوية ${x.priority}')));
Widget _scheduleTile(BuildContext c,AppState s,ScheduleItem x)=>Card(child:ListTile(leading:CircleAvatar(child:Text('${x.start.hour}')),title:Text(x.title),subtitle:Text('${x.subject} • ${x.minutes} دقيقة'),trailing:IconButton(onPressed:()=>s.toggleSchedule(x),icon:Icon(x.completed?Icons.check_circle:Icons.play_circle_outline))));
Widget _metric(String a,String b,IconData i,BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(10),child:Column(children:[Icon(i,color:Theme.of(c).colorScheme.primary),const SizedBox(height:4),Text(b,style:const TextStyle(fontWeight:FontWeight.w800)),Text(a,style:const TextStyle(fontSize:12))])));
void _addSubject(BuildContext c){final x=TextEditingController();showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('إضافة مادة'),content:TextField(controller:x,decoration:const InputDecoration(labelText:'اسم المادة')),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إلغاء')),FilledButton(onPressed:(){if(x.text.trim().isNotEmpty)AppState.instance.addSubject(x.text.trim());Navigator.pop(c);},child:const Text('حفظ'))]));}
void _addTask(BuildContext c,AppState s){final title=TextEditingController();String subject=s.subjects.isEmpty?'مذاكرة عامة':s.subjects.first.name;showDialog(context:c,builder:(_)=>StatefulBuilder(builder:(c,set)=>AlertDialog(title:const Text('إضافة مهمة'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'المهمة')),const SizedBox(height:10),DropdownButtonFormField<String>(value:subject,items:s.subjects.map((x)=>DropdownMenuItem(value:x.name,child:Text(x.name))).toList(),onChanged:(v)=>set(()=>subject=v!),decoration:const InputDecoration(labelText:'المادة'))]),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('إلغاء')),FilledButton(onPressed:(){if(title.text.trim().isNotEmpty)s.addTask(title.text.trim(),subject,dueDate:DateTime.now());Navigator.pop(c);},child:const Text('إضافة'))])));}
void _startSession(BuildContext c,AppState s){Navigator.of(c).push(MaterialPageRoute(builder:(_)=>const _SessionPage()));}
void _addExam(BuildContext c,AppState s){final t=TextEditingController();showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('اختبار جديد'),content:TextField(controller:t,decoration:const InputDecoration(labelText:'اسم الاختبار')),actions:[FilledButton(onPressed:(){if(t.text.trim().isNotEmpty)s.addExam(t.text.trim(),s.subjects.isEmpty?'عام':s.subjects.first.name,'كل الدروس',10);Navigator.pop(c);},child:const Text('إنشاء'))]));}
void _addSchedule(BuildContext c,AppState s){final t=TextEditingController();showDialog(context:c,builder:(_)=>AlertDialog(title:const Text('إضافة جلسة للخطة'),content:TextField(controller:t,decoration:const InputDecoration(labelText:'عنوان الجلسة')),actions:[FilledButton(onPressed:(){if(t.text.trim().isNotEmpty)s.addSchedule(t.text.trim(),s.subjects.isEmpty?'عام':s.subjects.first.name,DateTime.now().add(const Duration(hours:1)),45);Navigator.pop(c);},child:const Text('إضافة'))]));}
}
class _SessionPage extends StatefulWidget{const _SessionPage();@override State<_SessionPage> createState()=>_SessionPageState();}
class _SessionPageState extends State<_SessionPage>{int sec=25*60;bool run=false;@override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:const Text('جلسة مذاكرة')),body:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('${sec~/60}:${(sec%60).toString().padLeft(2,'0')}',style:const TextStyle(fontSize:56,fontWeight:FontWeight.w900)),const SizedBox(height:20),FilledButton.icon(onPressed:run?null:(){setState(()=>run=true);_tick();},icon:const Icon(Icons.play_arrow),label:const Text('بدء جلسة 25 دقيقة')),const SizedBox(height:10),OutlinedButton(onPressed:(){setState(()=>sec=25*60);},child:const Text('إعادة'))]));}void _tick(){Future.delayed(const Duration(seconds:1),(){if(!mounted||!run)return;if(sec>0){setState(()=>sec--);_tick();}else{setState(()=>run=false);AppState.instance.addSession('جلسة عامة',25);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('انتهت الجلسة 🎉 حان وقت الراحة 5 دقائق.')));}});} }
